## Preprocessing

In [105]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import pandas as pd
import numpy as np

In [106]:
#  Import and read the charity_data.csv.
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [107]:
#checking the dataframe
application_df.shape

(34299, 12)

In [108]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN", "NAME"], 1)
application_df.head()

<ipython-input-108-5608f9275d84>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN", "NAME"], 1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [109]:
#checking the dataframe again
application_df.shape

(34299, 10)

In [110]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [111]:
# Look at APPLICATION_TYPE value counts for binning
application_df["APPLICATION_TYPE"].value_counts()

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [112]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
# First, calculate the value counts and decide on a cutoff value for binning
cutoff_value = 528
# Find application types to replace based on the cutoff value
application_types_to_replace = [app_type for app_type, count in application_df['APPLICATION_TYPE'].value_counts().items() if count < cutoff_value]
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [113]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [114]:
# Look at CLASSIFICATION value counts for binning
application_df["CLASSIFICATION"].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [115]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# First, calculate the value counts for the 'CLASSIFICATION' column
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

# Then, filter these counts to only include classifications with a count greater than 1
classifications_greaterthan1 = classification_counts[classification_counts >1]
classifications_greaterthan1

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [118]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 1883

#find classification_to_replace based on cut off value = 1883
classifications_to_replace = [class_types for class_types, count in application_df["CLASSIFICATION"].value_counts().items() if count < cutoff_value]
#classifications_to_replace[0:5]
#giving variable name "other" to the classifications_to_replace list
Other = classifications_to_replace

In [117]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [119]:
# Convert categorical data to numeric with `pd.get_dummies`
#finding categorical columns first
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_cat

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [158]:
application_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   APPLICATION_TYPE        34299 non-null  object
 1   AFFILIATION             34299 non-null  object
 2   CLASSIFICATION          34299 non-null  object
 3   USE_CASE                34299 non-null  object
 4   ORGANIZATION            34299 non-null  object
 5   STATUS                  34299 non-null  int64
 6   INCOME_AMT              34299 non-null  object
 7   SPECIAL_CONSIDERATIONS  34299 non-null  object
 8   ASK_AMT                 34299 non-null  int64
 9   IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(3), object(7)
memory usage: 2.6+ MB

In [157]:
#finding numerical columns
application_num= application_df.dtypes[application_df.dtypes != "object"].index.tolist()
application_num

['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL']

In [122]:
# Check the number of unique values in each column
application_df[application_cat].nunique()

APPLICATION_TYPE          9
AFFILIATION               6
CLASSIFICATION            6
USE_CASE                  5
ORGANIZATION              4
INCOME_AMT                9
SPECIAL_CONSIDERATIONS    2
dtype: int64

In [166]:
# Convert categorical data to numeric with `pd.get_dummies`b
application_df_dummies = pd.get_dummies(application_df)
application_df_dummies

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [167]:
application_df_dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 44 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   STATUS                        34299 non-null  int64
 1   ASK_AMT                       34299 non-null  int64
 2   IS_SUCCESSFUL                 34299 non-null  int64
 3   APPLICATION_TYPE_Other        34299 non-null  uint8
 4   APPLICATION_TYPE_T10          34299 non-null  uint8
 5   APPLICATION_TYPE_T19          34299 non-null  uint8
 6   APPLICATION_TYPE_T3           34299 non-null  uint8
 7   APPLICATION_TYPE_T4           34299 non-null  uint8
 8   APPLICATION_TYPE_T5           34299 non-null  uint8
 9   APPLICATION_TYPE_T6           34299 non-null  uint8
 10  APPLICATION_TYPE_T7           34299 non-null  uint8
 11  APPLICATION_TYPE_T8           34299 non-null  uint8
 12  AFFILIATION_CompanySponsored  34299 non-null  uint8
 13  AFFILIATION_Family/Parent     34299 non-null  uint8
 14  AFFILIATION_Independent       34299 non-null  uint8
 15  AFFILIATION_National          34299 non-null  uint8
 16  AFFILIATION_Other             34299 non-null  uint8
 17  AFFILIATION_Regional          34299 non-null  uint8
 18  CLASSIFICATION_C1000          34299 non-null  uint8
 19  CLASSIFICATION_C1200          34299 non-null  uint8
 20  CLASSIFICATION_C2000          34299 non-null  uint8
 21  CLASSIFICATION_C2100          34299 non-null  uint8
 22  CLASSIFICATION_C3000          34299 non-null  uint8
 23  CLASSIFICATION_Other          34299 non-null  uint8
 24  USE_CASE_CommunityServ        34299 non-null  uint8
 25  USE_CASE_Heathcare            34299 non-null  uint8
 26  USE_CASE_Other                34299 non-null  uint8
 27  USE_CASE_Preservation         34299 non-null  uint8
 28  USE_CASE_ProductDev           34299 non-null  uint8
 29  ORGANIZATION_Association      34299 non-null  uint8
 30  ORGANIZATION_Co-operative     34299 non-null  uint8
 31  ORGANIZATION_Corporation      34299 non-null  uint8
 32  ORGANIZATION_Trust            34299 non-null  uint8
 33  INCOME_AMT_0                  34299 non-null  uint8
 34  INCOME_AMT_1-9999             34299 non-null  uint8
 35  INCOME_AMT_10000-24999        34299 non-null  uint8
 36  INCOME_AMT_100000-499999      34299 non-null  uint8
 37  INCOME_AMT_10M-50M            34299 non-null  uint8
 38  INCOME_AMT_1M-5M              34299 non-null  uint8
 39  INCOME_AMT_25000-99999        34299 non-null  uint8
 40  INCOME_AMT_50M+               34299 non-null  uint8
 41  INCOME_AMT_5M-10M             34299 non-null  uint8
 42  SPECIAL_CONSIDERATIONS_N      34299 non-null  uint8
 43  SPECIAL_CONSIDERATIONS_Y      34299 non-null  uint8
dtypes: int64(3), uint8(41)
memory usage: 2.1 MB

In [168]:
application_df_dummies.shape

(34299, 44)

In [169]:
application_df_dummies.columns

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T10', 'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3',
       'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6',
       'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'AFFILIATION_CompanySponsored', 'AFFILIATION_Family/Parent',
       'AFFILIATION_Independent', 'AFFILIATION_National', 'AFFILIATION_Other',
       'AFFILIATION_Regional', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000',
       'CLASSIFICATION_Other', 'USE_CASE_CommunityServ', 'USE_CASE_Heathcare',
       'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M',
       'INCOME_AMT_25000-99999', 'INCOME_AMT_50M+', 'INCOME_AMT_5M-10M',
       'SPECIAL_CONSIDERATIONS_N', 'SPECIAL_CONSIDERATIONS_Y'],
      dtype='object')

In [170]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"].values
X = application_df_dummies.drop(["IS_SUCCESSFUL"],1).values
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=45)

<ipython-input-170-9447856a5859>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = application_df_dummies.drop(["IS_SUCCESSFUL"],1).values

In [190]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [191]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2, activation = "relu")

)

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 80)                3520

 dense_16 (Dense)            (None, 30)                2430

 dense_17 (Dense)            (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [192]:
# Compile the model
nn.compile(loss = "binary_crossentropy", optimizer= "adam", metrics = ["accuracy"])

In [193]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5715 - accuracy: 0.7210
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5565 - accuracy: 0.7308
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5532 - accuracy: 0.7318
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7323
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7325
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7335
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7335
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7336
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7334
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7347
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5457 - accuracy: 0.7348
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5456 - accuracy: 0.7361
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7353
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7365
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7362
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7362
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7365
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7369
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7362
Epoch 20/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7371
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7376
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7377
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7379
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7369
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7367
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7382
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7370
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5408 - accuracy: 0.7381
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7381
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7381
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7384
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7384
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7385
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7386
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7385
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7383
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7388
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7393
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7388
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7395
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7390
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7397
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7391
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7397
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7391
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7405
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7400
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7397
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7403
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7404
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7400
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7414
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7397
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7404
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7404
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7401
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7398
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7403
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7403
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7403
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7406
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7395
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7405
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7401
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7406
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7406
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7402
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7406
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7415
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7409
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7407
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7413
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7411
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7410
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7411
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7408
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7403
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7404
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7409
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7400
Epoch 81/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7411
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7405
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7407
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7412
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7406
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7420
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7411
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7414
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7411
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7415
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7419
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7409
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7415
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7415
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7418
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7417
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7412
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7421
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7420
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7415

In [2]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

NameError: name 'nn' is not defined

In [175]:
#importing dependencies
from keras.models import Sequential
from keras.models import load_model

In [1]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

# To load the model back from the file
loaded_model = load_model('AlphabetSoupCharity.h5')

NameError: name 'nn' is not defined